Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.define 'idouidiS' do |server|
		config.vm.network "private_network", ip: "192.168.56.110"
		# Share an additional folder to the guest VM. The first argument is
		# the path on the host to the actual folder. The second argument is
		# the path on the guest to mount the folder. And the optional third
		# argument is a set of non-required options.
		server.vm.synced_folder ".", "/vagrant_data", type: "rsync",
		rsync__exclude: ["Vagrantfile"]

		
		# Disable the default share of the current code directory. Doing this
		# provides improved isolation between the vagrant box and your host
		# by making sure your Vagrantfile isn't accessible to the vagrant box.
		# If you use this you may want to enable additional shared subfolders as
		# shown above.
		# config.vm.synced_folder ".", "/vagrant", disabled: true
		
		# Provider-specific configuration so you can fine-tune various
		# backing providers for Vagrant. These expose provider-specific options.
		# Example for VirtualBox:
		#
		config.vm.provider "virtualbox" do |vb|
		  vb.memory = "1024"
		  vb.cpus = 1
		end
		#
		# View the documentation for the provider you are using for more
		# information on available options.
		
		# Enable provisioning with a shell script. Additional provisioners such as
		# Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
		# documentation for more information about their specific syntax and use.
		config.vm.provision "shell", inline: <<-SHELL
			apt-get update && apt-get upgrade -y
			curl -sfL https://get.k3s.io |  INSTALL_K3S_EXEC="--node-ip=192.168.56.110" sh -	
			kubectl apply -f /vagrant_data/apps.yaml
			kubectl apply -f /vagrant_data/ingress.yaml
		SHELL
	end
end
