Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.define 'idouidiS' do |server|

		config.vm.network "private_network", ip: "192.168.56.110"
		server.vm.synced_folder ".", "/vagrant_data", type: "rsync",
      rsync__exclude: ["Vagrantfile"]

		config.vm.provider "virtualbox" do |vb|
		  vb.memory = "1024"
		  vb.cpus = 1
		end

		config.vm.provision "shell", inline: <<-SHELL
			apt-get update && apt-get upgrade -y
			curl -sfL https://get.k3s.io |  INSTALL_K3S_EXEC="--node-ip=192.168.56.110" sh -	
			kubectl apply -R -f /vagrant_data/confs/
		SHELL
    
	end
end
