Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.define 'asimonS' do |server|
    server.vm.hostname = 'asimonS'
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

    server.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update && apt-get upgrade -y
      ufw disable
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-ip=192.168.56.110" sh -
      if [ -d /var/lib/rancher/k3s/ ]; then
        sudo cat /var/lib/rancher/k3s/server/token > /vagrant/.token
      else
        echo "Error while k3s installation"
        echo "Exit"
        exit 1
      fi
    SHELL
  end

  config.vm.define 'asimonSW' do |worker|
    worker.vm.hostname = 'asimonSW'
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = '1024'
      vb.cpus = 1
    end
    worker.vm.provision 'shell', inline: <<-SHELL
      apt-get update && apt-get upgrade -y
      curl -sfL https://get.k3s.io | K3S_URL='https://192.168.56.110:6443' K3S_TOKEN=$(cat /vagrant/.token) INSTALL_K3S_EXEC="--node-ip=192.168.56.111" sh -
    SHELL
  end
end
