Vagrant.configure("2") do |config|

  config.vm.define 'asimonS' do |server|
    server.vm.box = "ubuntu/bionic64"
    server.vm.hostname = 'asimonS'
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

    server.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update && apt-get upgrade -y
      echo '=> Start k3s instalation'
      curl -sSL https://get.k3s.io | sh
      if [ -d /var/lib/rancher/k3s ]; then
        sudo cat /var/lib/rancher/k3s/server/node-token > /vagrant/.token
      else
        echo 'An error occured durring k3s installation\n'
        echo 'Exiting'
        exit 1
      fi
    SHELL
  end

  config.vm.define 'asimonSW' do |worker|
    worker.vm.box = "ubuntu/bionic64"
    worker.vm.hostname = 'asimonSW'
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = '1024'
      vb.cpus = 1
    end
    worker.vm.provision 'shell', inline: <<-SHELL
      apt-get update && apt-get upgrade -y
      curl -sSL https://get.k3s.io | K3S_TOKEN=$(cat /vagrant/.token) K3S_URL=https://192.168.56.110:6343 sh
    SHELL
  end
end
