apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground-app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playground
  template:
    metadata:
      labels:
        app: playground
    spec:
      containers:
      - name: playground-container
        image: wil42/playground
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: playground-service
  namespace: dev
spec:
  selector:
    app: playground
  ports:
  - protocol: TCP
    port: 8888        # Port exposé à l'extérieur
    targetPort: 8888  # Port interne de l'application dans le conteneur
  type: LoadBalancer
